# Generated by Django 5.2.13 on 2026-05-04 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('supplier', models.CharField(blank=True, max_length=120)),
                ('memo', models.TextField(blank=True)),
                ('cost_mode', models.CharField(choices=[('none', '原価計算しない'), ('same_unit', '仕入単位のまま計算'), ('conversion', '使用単位に換算して計算')], default='none', max_length=20)),
                ('purchase_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conversion_from_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conversion_to_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('conversion_from_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversion_from_ingredients', to='api.unit')),
                ('conversion_to_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversion_to_ingredients', to='api.unit')),
                ('purchase_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_ingredients', to='api.unit')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='api.shop')),
                ('usage_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usage_ingredients', to='api.unit')),
            ],
            options={
                'ordering': ['name', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('shop', 'name'), name='unique_active_ingredient_shop_name')],
            },
        ),
    ]
