# Generated by Django 5.2.13 on 2026-05-04 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recipe_recipeingredient_recipestep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('planned_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('todo', '未着手'), ('doing', '作業中'), ('done', '完了')], default='todo', max_length=20)),
                ('memo', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('planned_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prep_tasks', to='api.unit')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prep_tasks', to='api.recipe')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_tasks', to='api.shop')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
