# Generated by Django 5.2.13 on 2026-07-11 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_preptask'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_memos', to='api.shop')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
