# Generated by Django 5.2.13 on 2026-07-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_boardmemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('prep', '仕込み用'), ('menu', '販売商品')], default='prep', max_length=20),
        ),
    ]
