# Generated by Django 5.2.13 on 2026-07-27 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_recipe_recipe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.CharField(choices=[('raw', '通常材料'), ('prep_recipe', '仕込みレシピ')], default='raw', max_length=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='source_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredient_links', to='api.recipe'),
        ),
    ]
