# Generated by Django 5.2.13 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_ingredient_ingredient_type_ingredient_source_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="demo_key",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=80,
                null=True,
                unique=True,
            ),
        ),
    ]
