"""
Django settings for ricetta project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env(name, default=''):
    value = os.getenv(name)
    if value is None or value == '':
        return default
    return value


def env_bool(name, default=False):
    return env(name, str(default)).lower() in ('1', 'true', 'yes', 'on')


def production_env(name):
    value = os.getenv(name, '').strip()
    lowered = value.lower()
    placeholder_markers = (
        'change-me',
        'django-insecure',
        'example.com',
        'replace-me',
    )
    if not value:
        raise ImproperlyConfigured(f'{name} is required when DJANGO_DEBUG is false.')
    if any(marker in lowered for marker in placeholder_markers):
        raise ImproperlyConfigured(
            f'{name} must not use a development or placeholder value when DJANGO_DEBUG is false.'
        )
    return value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

DEMO_MODE = env_bool('DEMO_MODE', False)

if DEBUG:
    SECRET_KEY = env('DJANGO_SECRET_KEY', 'django-insecure-dev-only-change-me')
    allowed_hosts_value = env('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')
    csrf_trusted_origins_value = env(
        'DJANGO_CSRF_TRUSTED_ORIGINS',
        'http://localhost:5173,http://localhost:5174',
    )
else:
    SECRET_KEY = production_env('DJANGO_SECRET_KEY')
    if len(SECRET_KEY) < 50:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY must be at least 50 characters when DJANGO_DEBUG is false.'
        )
    allowed_hosts_value = production_env('DJANGO_ALLOWED_HOSTS')
    csrf_trusted_origins_value = production_env('DJANGO_CSRF_TRUSTED_ORIGINS')

ALLOWED_HOSTS = [
    host.strip() for host in allowed_hosts_value.split(',') if host.strip()
]
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in csrf_trusted_origins_value.split(',')
    if origin.strip()
]

if not DEBUG:
    if '*' in ALLOWED_HOSTS or any(
        host in {'localhost', '127.0.0.1', '::1'} for host in ALLOWED_HOSTS
    ):
        raise ImproperlyConfigured(
            'DJANGO_ALLOWED_HOSTS must contain only explicit production hosts.'
        )
    if any(not origin.startswith('https://') for origin in CSRF_TRUSTED_ORIGINS):
        raise ImproperlyConfigured(
            'DJANGO_CSRF_TRUSTED_ORIGINS must contain only HTTPS origins in production.'
        )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
]

REST_FRAMEWORK = {
    'NUM_PROXIES': 1,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'login': '5/minute',
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ricetta.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ricetta.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if DEBUG and not env('POSTGRES_HOST'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    if DEBUG:
        postgres_name = env('POSTGRES_DB', 'ricetta')
        postgres_user = env('POSTGRES_USER', 'ricetta')
        postgres_password = env('POSTGRES_PASSWORD', 'ricetta')
        postgres_host = env('POSTGRES_HOST', 'db')
        postgres_port = env('POSTGRES_PORT', '5432')
    else:
        postgres_name = production_env('POSTGRES_DB')
        postgres_user = production_env('POSTGRES_USER')
        postgres_password = production_env('POSTGRES_PASSWORD')
        postgres_host = production_env('POSTGRES_HOST')
        postgres_port = production_env('POSTGRES_PORT')
        if not postgres_port.isdigit():
            raise ImproperlyConfigured(
                'POSTGRES_PORT must be numeric when DJANGO_DEBUG is false.'
            )

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': postgres_name,
            'USER': postgres_user,
            'PASSWORD': postgres_password,
            'HOST': postgres_host,
            'PORT': postgres_port,
        }
    }


SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_HSTS_SECONDS = 0 if DEBUG else 3600
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
